Repository ValidereInc/common-components, pull requests merged in 2021-12, with the labels that each got.

#392 [V360-8809] feat testing : Alert test cases
  package.json
  src/Alert/Alert.module.scss
  src/Alert/Alert.test.js
  src/Alert/Alert.tsx
  src/Alert/AlertHelper.test.js
  src/Alert/AlertProvider.test.js
  src/Alert/AlertProvider.tsx
  src/Alert/useManageAlerts.tsx
Labels: enhancement

#421 Release 1.0.16
  development/dist/bundle.js
  development/dist/main.css
  development/package.json
  dist/bundle.js
  dist/main.css
  package.json
Labels: release

#422 release-1.0.17
  development/dist/bundle.js
  development/package.json
  dist/bundle.js
  package.json
Labels: release

#426 fix(form): increase select menu index to be the highest
  src/Form/FormInputs/SelectInput/SelectInput.tsx
Labels: bug

#428 release-1.0.18
  development/dist/bundle.js
  development/package.json
  dist/bundle.js
  package.json
Labels: release
