Repository ValidereInc/common-components, pull requests merged in 2021-09, with the labels that each got.

#173 Add common modal component
  .storybook/Introduction.stories.mdx
  development/dist/bundle.js
  development/package.json
  dist/bundle.js
  package-lock.json
  package.json
  src/Modal/Modal.js
  src/Modal/Modal.scss
  src/Modal/Modal.stories.js
  src/Modal/Modal.test.js
  src/index.js
Labels: enhancement, dependencies

#183 fix(package): update storybook packages
  package-lock.json
  package.json
Labels: dependencies

#182 Add global z-index values
  .storybook/main.js
  development/dist/bundle.js
  development/package.json
  dist/bundle.js
  postcss.config.js
  src/Loader/LoadingBar.js
  src/Modal/Modal.scss
  src/Sidebar/Sidebar.scss
  src/Table/Datatable.css
  src/zIndex.js
  src/zindex-vars.json
Labels: enhancement

#192 Make Modal.Header have a close button by default
  development/dist/bundle.js
  dist/bundle.js
  src/Modal/Modal.js
  src/Modal/Modal.stories.js
Labels: bug
